meta_product_name: "Yuanyuan Zhu"
meta_title: "Yuanyuan Zhu - Full Stack Web Developer"
meta_description: "Hi, my name is Yuanyuan Zhu. I am a self-motivated Full Stack Developer. I am open to full-time, part-time and freelance work opportunities."
meta_image: "cover.png"
