meta_product_name: "Yuanyuan Zhu"
meta_title: "Yuanyuan Zhu [Full Stack Web Developer]"
meta_description: "Positive Attitude | Curious | Detail Oriented | Big Picture Focused | Good Time and Task Management"
meta_image: "cover.png"
