meta_product_name: "Yuanyuan Zhu"
meta_title: "Yuanyuan Zhu [Full Stack Web Developer]"
meta_description: "Tech Skills: Ruby | Rails | HTML | CSS | JavaScript | Bootstrap | React.js | Figma | MySQL | PostgreSQL | Git | Heroku | Cloudinary | Pundit | Devise | Next.js | Socket.io\n
                   Soft Skills: Positive Attitude | Curious | Detail Oriented | Big Picture Focused | Good Time and Task Management"
meta_image: "cover.png"
